apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  replicas: {{ .Values.python.replicas }}
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: {{ .Values.python.image }}
        env:
        - name: REDIS_HOST
          value: {{ .Values.python.redis.host }}
        - name: REDIS_PORT
          value: "{{ .Values.python.redis.port }}"
        ports:
        - containerPort: 5000
        livenessProbe:
          tcpSocket:
            port: 5000
      imagePullSecrets:
      - name: pullsecret

---
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.pullSecret }}
kind: Secret
metadata:
  name: pullsecret

---
apiVersion: v1
kind: Service
metadata:
  name: python-svc
spec:
  selector:
    app: python
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
